name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: '20'
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Compile and Build Web App
        run: npm run build
        env:
          # If typescript lint fails or warning occurs, we can build anyway
          CI: false

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the build script generates (client-side build assets)
          branch: gh-pages # The branch the action will deploy to
          token: ${{ secrets.GITHUB_TOKEN }}
